dataset: MikiV/SimpleStories-SimpleStories-chunked-128

model_shape:
  layers: 6
  d_model: 384
  n_heads: 6
  d_vocab: 4096

# Training hyperparameters
batch_size: 128
seq_len: 128
samples: 1000
gradient_accumulation_steps: 1
learning_rate: 1e-3
lr_warmup_steps: 1000
weight_decay: 0.01
eval_interval: 100

validation_batch_size: 2048
validation_batches: 50

# Wandb configuration
wandb_entity: miki-and-tml
wandb_project: scaling-tests
