[project]
authors = ["Miki Vanoušek <vanousekmikulas@gmail.com>"]
channels = ["conda-forge"]
name = "scaling"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
# cuda = "12.0"

[dependencies]
pytorch = "*"
# pytorch-gpu = "*"

python = "3.13.*"
ipykernel = ">=6.30.1,<7"
ipywidgets = ">=8.1.7,<9"
transformers = ">=4.56.2,<5"
markupsafe = ">=3.0.2,<4"
pillow = ">=11.3.0,<12"
matplotlib = ">=3.10.6,<4"
python-dotenv = ">=1.1.1,<2"
wandb = ">=0.21.1,<0.22"
