runai submit \
  -p tml-vanousek \
  --job-name-prefix train \
  --image ic-registry.epfl.ch/tml/tml:v2 \
  --pvc tml-scratch:/tmlscratch \
  --working-dir / \
  -e USER_HOME=/tmlscratch/vanousek \
  -e HOME=/tmlscratch/vanousek \
  -e USER=vanousek \
  -e UID=1000 \
  -e GROUP=TML-unit \
  -e GID=11180 \
  -e HF_TOKEN=SECRET:my-secret,hf_token\
  -e WANDB_API_KEY=SECRET:my-secret,wandb_api_key\
  --cpu 1 \
  --cpu-limit 16 \
  --gpu 1 \
  --run-as-uid 1000 \
  --run-as-gid 11180 \
  --working-dir / \
  --image-pull-policy IfNotPresent \
  --memory 8G \
  --tty \
  --stdin \
  --allow-privilege-escalation \
  --interactive
