train_dataset:
  name: MikiV/SimpleStories-SimpleStories-subchunked-32x4
  split: train
validation_datasets:
  - name: MikiV/SimpleStories-SimpleStories-subchunked-16x8
    split: validation
  - name: MikiV/SimpleStories-SimpleStories-subchunked-32x4
    split: validation
  - name: MikiV/SimpleStories-SimpleStories-subchunked-64x2
    split: validation
  - name: MikiV/SimpleStories-SimpleStories-chunked-128
    split: validation

model_shape:
  layers: 6
  d_model: 256
  n_heads: 4
  d_vocab: 4096

# Training hyperparameters
batch_size: 256
context_length: 32
tokens: 480000000

gradient_accumulation_steps: 1
learning_rate: 1e-4
lr_warmup_steps: 100
weight_decay: 0.01

eval_interval: -1
validation_batch_size: 4096

# Wandb configuration
wandb_entity: miki-and-tml
wandb_project: scaling-tests
