train_dataset:
  name: MikiV/Ultra-FineWeb-chunked-8192
  split: train
validation_datasets:
  - name: MikiV/Ultra-FineWeb-chunked-8192
    split: train
  - name: MikiV/Ultra-FineWeb-chunked-4x2048
    split: train

model_shape:
  layers: 12
  d_model: 768
  n_heads: 12
  d_vocab: 50_257

# Training hyperparameters
batch_size: 64
context_length: 8192
tokens: 52428800

learning_rate: 1e-3
lr_warmup_steps: 100
weight_decay: 0.01

eval_interval: -1
validation_batch_size: 512

# Wandb configuration
wandb_entity: miki-and-tml
wandb_project: scaling-tests
hf_upload_username: MikiV
